apiVersion: v1
kind: Secret
metadata:
  name: {{ include "legalease-ai.fullname" . }}-secret
  labels:
    {{- include "legalease-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  PINECONE_API_KEY: {{ .Values.secrets.pineconeApiKey | quote }}
  PINECONE_ENVIRONMENT: {{ .Values.secrets.pineconeEnvironment | quote }}