apiVersion: v2
name: legalease-ai
description: A Helm chart for LegalEase AI application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - legal
  - ai
  - document-analysis
home: https://legalease-ai.com
sources:
  - https://github.com/legalease-ai/legalease-ai
maintainers:
  - name: LegalEase AI Team
    email: dev@legalease-ai.com
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: rabbitmq
    version: "11.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.enabled