apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: legalease-ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: legalease-ai/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: legalease-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: legalease-config
              key: REDIS_URL
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: legalease-config
              key: RABBITMQ_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: legalease-secrets
              key: SECRET_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: legalease-secrets
              key: OPENAI_API_KEY
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: legalease-secrets
              key: PINECONE_API_KEY
        - name: PINECONE_ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: legalease-secrets
              key: PINECONE_ENVIRONMENT
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        volumeMounts:
        - name: uploaded-files
          mountPath: /app/uploads
      volumes:
      - name: uploaded-files
        persistentVolumeClaim:
          claimName: uploaded-files-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: legalease-ai
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploaded-files-pvc
  namespace: legalease-ai
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi